//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketTRN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseTypeJobGroup
    {
        public int CourseTypeId { get; set; }
        public int JobGroupId { get; set; }
        public string Remark { get; set; }
    
        public virtual CourseType CourseType { get; set; }
        public virtual JobGroup JobGroup { get; set; }
    }
}
