//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFBVoyageReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EFBVoyageReport()
        {
            this.EFBFlightIrregularities = new HashSet<EFBFlightIrregularity>();
            this.EFBReasons = new HashSet<EFBReason>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FlightId { get; set; }
        public string Route { get; set; }
        public Nullable<int> RestReduction { get; set; }
        public Nullable<int> DutyExtention { get; set; }
        public string Report { get; set; }
        public Nullable<System.DateTime> DatePICSignature { get; set; }
        public Nullable<int> ActionedById { get; set; }
        public Nullable<System.DateTime> DateActioned { get; set; }
        public Nullable<System.DateTime> DateConfirmed { get; set; }
        public Nullable<int> DepDelay { get; set; }
        public string DateUpdate { get; set; }
        public string User { get; set; }
        public string JLSignedBy { get; set; }
        public Nullable<System.DateTime> JLDatePICApproved { get; set; }
        public Nullable<int> PICId { get; set; }
        public string PIC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFBFlightIrregularity> EFBFlightIrregularities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFBReason> EFBReasons { get; set; }
    }
}
